[package]
name = "kazari_server"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
log = "0"
hashbrown = "0"
downcast-rs = { version = "1.2.0", default-features = false }

kazari_common = { "path" = "../common" }

[dev-dependencies]
pretty_assertions = "0"
